AllCops:
  TargetRubyVersion: 2.7
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - "vendor/**/*"

Gemspec/DevelopmentDependencies:
  Enabled: false

Layout/LineLength:
  Enabled: false

Lint/AmbiguousOperatorPrecedence:
  Enabled: false

Lint/FloatComparison:
  Enabled: false

Metrics:
  Enabled: false

Naming/MethodParameterName:
  Enabled: false

Style/ComparableClamp:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/MultipleComparison:
  Enabled: false

Style/RedundantParentheses:
  Enabled: false

Style/SafeNavigation:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/SymbolProc:
  Enabled: false

Style/TernaryParentheses:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - "spec/**/*"
