AllCops:
  TargetRubyVersion: 2.7
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - "vendor/**/*"

# GitHub Ruby style
inherit_gem:
  rubocop-github:
    - config/default.yml

# Overwrite or add rules to create your own house style
#
# # Use `[a, [b, c]]` not `[ a, [ b, c ] ]`
# Layout/SpaceInsideArrayLiteralBrackets:
#   Enabled: false


Metrics/BlockLength:
  Exclude:
    - "spec/**/*"